on:
  push:
    branches:
      - master
permissions:
  contents: write
  pull-requests: read

name: Release
jobs:
  release:
    name: Run Dsync Release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Dependencies
        run: sudo apt-get install -y make gcc-14

      - name: Create Tag
        id: tag_generator
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false

      - name: Create Binary
        run: make

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dsync
          generate_release_notes: true
          make_latest: true
          tag_name: ${{ steps.tag_generator.outputs.tag }}
